### ISSUE TITLE
Refactor code base

### ISSUE THREAD

**Issue by kgonzago** [Esri/solutions-grg-widget#132]
Before the GRG widget can be added to the WAB code base to have it included in the pool of core widgets for 6.1 release, we will need to review the widget from code and UI perspectives. Below is a list of high-level topics that will guide this epic:

- [ ] The code base will need to be refactored before its inclusion into core WAB. This is captured in #131 and #138.

- [ ] We want to promote code readability and also adhere to best practices for JS coding ([coding guidelines](https://devtopia.esri.com/WebGIS/arcgis-js-api/wiki/Dev-Guidelines) from JS Dev Team). This is captured in #136.

- [ ] Review UI and determine if it adheres to WAB [design guidelines](https://esri.app.box.com/file/35183397417). This is captured in #137.

**Comment by lfunkhouser** [comment]
@kgonzago please provide more information on what this means.

**Comment by kgonzago** [comment]
@lfunkhouser @topowright 

I added additional information to this epic and tied four issues to it. Hopefully, what I added will be sufficient to remove any confusion. Let me know if more info is needed.

**Comment by topowright** [comment]
@adgiles is this still needed being that we are now further along in the process?

**Comment by adgiles** [comment]
@topowright no refactoring of the code base has taken place

**Comment by kgonzago** [comment]
Looks like it is not needed since Junshan already completed his initial code review without a comment regarding code refactor.

**Comment by kgonzago** [comment]
We can close out this epic or temporarily place it on the back burner.

**Comment by lfunkhouser** [comment]
Closing. Will create a new issue/epic if this is required.
